In [107]:
# %pip uninstall numpy pandas scipy mne
# %pip install numpy pandas scipy mne

import numpy as np
import pandas as pd
import mne

In [108]:
a = pd.read_csv('C:/bt23ece064/dataset/annotations_2017_A_fixed.csv')
b = pd.read_csv('C:/bt23ece064/dataset/annotations_2017_B.csv')
c = pd.read_csv('C:/bt23ece064/dataset/annotations_2017_C.csv')

In [109]:
# Your bipolar_pairs list
bipolar_pairs = [
    ('EEG Fp1-REF', 'EEG F7-REF'),
    ('EEG F7-REF',  'EEG T3-REF'),
    ('EEG T3-REF',  'EEG T5-REF'),
    ('EEG T5-REF',  'EEG O1-REF'),
    ('EEG Fp1-REF', 'EEG F3-REF'),
    ('EEG F3-REF',  'EEG C3-REF'),
    ('EEG C3-REF',  'EEG P3-REF'),
    ('EEG P3-REF',  'EEG O1-REF'),
    ('EEG Fz-REF',  'EEG Cz-REF'),
    ('EEG Cz-REF',  'EEG Pz-REF'),
    ('EEG Fp2-REF', 'EEG F4-REF'),
    ('EEG F4-REF',  'EEG C4-REF'),
    ('EEG C4-REF',  'EEG P4-REF'),
    ('EEG P4-REF',  'EEG O2-REF'),
    ('EEG Fp2-REF', 'EEG F8-REF'),
    ('EEG F8-REF',  'EEG T4-REF'),
    ('EEG T4-REF',  'EEG T6-REF'),
    ('EEG T6-REF',  'EEG O2-REF'),
]

desired_order = [
    'Fp2-F4', 'F4-C4', 'C4-P4', 'P4-O2',
    'Fp1-F3', 'F3-C3', 'C3-P3', 'P3-O1',
    'Fp2-F8', 'F8-T4', 'T4-T6', 'T6-O2',
    'Fp1-F7', 'F7-T3', 'T3-T5', 'T5-O1',
    'Fz-Cz', 'Cz-Pz',
]

def pair_name(pair):
    # Extract labels removing 'EEG ' and '-REF'
    left = pair[0].replace('EEG ', '').replace('-REF', '')
    right = pair[1].replace('EEG ', '').replace('-REF', '')
    return f"{left}-{right}"

# Create a dict from name to pair for quick lookup
name_to_pair = {pair_name(p): p for p in bipolar_pairs}

# Reorder bipolar_pairs according to desired_order
reordered_pairs = [name_to_pair[name] for name in desired_order]

# Let's print to verify
for name, pair in zip(desired_order, reordered_pairs):
    print(f"{name}: {pair}")

Fp2-F4: ('EEG Fp2-REF', 'EEG F4-REF')
F4-C4: ('EEG F4-REF', 'EEG C4-REF')
C4-P4: ('EEG C4-REF', 'EEG P4-REF')
P4-O2: ('EEG P4-REF', 'EEG O2-REF')
Fp1-F3: ('EEG Fp1-REF', 'EEG F3-REF')
F3-C3: ('EEG F3-REF', 'EEG C3-REF')
C3-P3: ('EEG C3-REF', 'EEG P3-REF')
P3-O1: ('EEG P3-REF', 'EEG O1-REF')
Fp2-F8: ('EEG Fp2-REF', 'EEG F8-REF')
F8-T4: ('EEG F8-REF', 'EEG T4-REF')
T4-T6: ('EEG T4-REF', 'EEG T6-REF')
T6-O2: ('EEG T6-REF', 'EEG O2-REF')
Fp1-F7: ('EEG Fp1-REF', 'EEG F7-REF')
F7-T3: ('EEG F7-REF', 'EEG T3-REF')
T3-T5: ('EEG T3-REF', 'EEG T5-REF')
T5-O1: ('EEG T5-REF', 'EEG O1-REF')
Fz-Cz: ('EEG Fz-REF', 'EEG Cz-REF')
Cz-Pz: ('EEG Cz-REF', 'EEG Pz-REF')

In [110]:
bipolar_pairs = [
    ('EEG Fp1-REF', 'EEG F7-REF'),
    ('EEG F7-REF',  'EEG T3-REF'),
    ('EEG T3-REF',  'EEG T5-REF'),
    ('EEG T5-REF',  'EEG O1-REF'),
    ('EEG Fp1-REF', 'EEG F3-REF'),
    ('EEG F3-REF',  'EEG C3-REF'),
    ('EEG C3-REF',  'EEG P3-REF'),
    ('EEG P3-REF',  'EEG O1-REF'),
    ('EEG Fz-REF',  'EEG Cz-REF'),
    ('EEG Cz-REF',  'EEG Pz-REF'),
    ('EEG Fp2-REF', 'EEG F4-REF'),
    ('EEG F4-REF',  'EEG C4-REF'),
    ('EEG C4-REF',  'EEG P4-REF'),
    ('EEG P4-REF',  'EEG O2-REF'),
    ('EEG Fp2-REF', 'EEG F8-REF'),
    ('EEG F8-REF',  'EEG T4-REF'),
    ('EEG T4-REF',  'EEG T6-REF'),
    ('EEG T6-REF',  'EEG O2-REF'),
]

def normalize_channel(ch):
    return ch.strip().upper()

bipolar_pairs = [(normalize_channel(a), normalize_channel(b)) for a, b in bipolar_pairs]

def make_ch_names(pairs):
    def pretty(ch):
        return ch.replace('EEG ', '').replace('-REF', '').capitalize()
    return [f"{pretty(a)}-{pretty(b)}" for a, b in pairs]

anode = [a for a, _ in bipolar_pairs]
cathode = [b for _, b in bipolar_pairs]
ch_names = make_ch_names(reordered_pairs)

In [111]:

def getArray(filename: str):
    raw = mne.io.read_raw_edf(filename, preload=True)
    raw.rename_channels(lambda ch: ch.upper())
    drop_candidates = ['ECG EKG', 'RESP EFFORT','ECG EKG-REF','RESP EFFORT-REF']
    available = set(raw.ch_names)
    to_drop = [ch for ch in drop_candidates if ch in available]
    if to_drop:
        raw.drop_channels(to_drop)
    raw = mne.set_bipolar_reference(raw, anode=anode, cathode=cathode, ch_name=ch_names, copy=True)
    array = raw.get_data()
    # raw.plot()
    return array

In [ ]:
import os

eeg_set = []
for i in range(1, 80):
    filepath = f'C:/bt23ece064/dataset/eeg{i}.edf'
    if os.path.exists(filepath):
        try:
            eeg = getArray(filepath)
            eeg_set.append(eeg)
        except ValueError as e:
            print(f"Error in file: {filepath}")
            print(e)

Extracting EDF parameters from C:\bt23ece064\dataset\eeg1.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1790207  =      0.000 ...  6992.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1790208
    Range : 0 ... 1790207 =      0.000 ...  6992.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg2.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 962815  =      0.000 ...  3760.996 secs...
Creating RawArray with float64 data, n_channels=18, n_times=1203456
    Range : 0 ... 1203455 =      0.000 ...  4700.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg52.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1003519  =      0.000 ...  3919.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1003520
    Range : 0 ... 1003519 =      0.000 ...  3919.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg53.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 888319  =      0.000 ...  3469.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=962816
    Range : 0 ... 962815 =      0.000 ...  3760.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg3.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1129471  =      0.000 ...  4411.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1129472
    Range : 0 ... 1129471 =      0.000 ...  4411.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg4.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 876799  =      0.000 ...  3424.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=876800
    Range : 0 ... 876799 =      0.000 ...  3424.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg5.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 983295  =      0.000 ...  3840.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=983296
    Range : 0 ... 983295 =      0.000 ...  3840.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg6.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1203967  =      0.000 ...  4702.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1203968
    Range : 0 ... 1203967 =      0.000 ...  4702.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg7.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 935423  =      0.000 ...  3653.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=935424
    Range : 0 ... 935423 =      0.000 ...  3653.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg8.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1180927  =      0.000 ...  4612.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1180928
    Range : 0 ... 1180927 =      0.000 ...  4612.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg9.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 908799  =      0.000 ...  3549.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=908800
    Range : 0 ... 908799 =      0.000 ...  3549.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg10.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1389311  =      0.000 ...  5426.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1389312
    Range : 0 ... 1389311 =      0.000 ...  5426.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg11.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1916927  =      0.000 ...  7487.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1916928
    Range : 0 ... 1916927 =      0.000 ...  7487.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg12.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1143807  =      0.000 ...  4467.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1143808
    Range : 0 ... 1143807 =      0.000 ...  4467.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg13.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 3946495  =      0.000 ... 15415.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=3946496
    Range : 0 ... 3946495 =      0.000 ... 15415.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg14.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 953855  =      0.000 ...  3725.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=953856
    Range : 0 ... 953855 =      0.000 ...  3725.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg15.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1765887  =      0.000 ...  6897.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1765888
    Range : 0 ... 1765887 =      0.000 ...  6897.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg16.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1520895  =      0.000 ...  5940.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1520896
    Range : 0 ... 1520895 =      0.000 ...  5940.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg17.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1406207  =      0.000 ...  5492.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1406208
    Range : 0 ... 1406207 =      0.000 ...  5492.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg18.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 934655  =      0.000 ...  3650.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=934656
    Range : 0 ... 934655 =      0.000 ...  3650.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg19.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 2305535  =      0.000 ...  9005.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=2305536
    Range : 0 ... 2305535 =      0.000 ...  9005.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg20.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1020671  =      0.000 ...  3986.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1020672
    Range : 0 ... 1020671 =      0.000 ...  3986.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg21.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1460991  =      0.000 ...  5706.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1460992
    Range : 0 ... 1460991 =      0.000 ...  5706.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg22.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 984063  =      0.000 ...  3843.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=984064
    Range : 0 ... 984063 =      0.000 ...  3843.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg23.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1134847  =      0.000 ...  4432.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1134848
    Range : 0 ... 1134847 =      0.000 ...  4432.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg24.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 948735  =      0.000 ...  3705.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=948736
    Range : 0 ... 948735 =      0.000 ...  3705.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg25.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1717503  =      0.000 ...  6708.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1717504
    Range : 0 ... 1717503 =      0.000 ...  6708.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg26.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1070591  =      0.000 ...  4181.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1070592
    Range : 0 ... 1070591 =      0.000 ...  4181.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg27.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 894975  =      0.000 ...  3495.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=894976
    Range : 0 ... 894975 =      0.000 ...  3495.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg28.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1473791  =      0.000 ...  5756.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1473792
    Range : 0 ... 1473791 =      0.000 ...  5756.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg29.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 2057471  =      0.000 ...  8036.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=2057472
    Range : 0 ... 2057471 =      0.000 ...  8036.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg30.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1007871  =      0.000 ...  3936.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1007872
    Range : 0 ... 1007871 =      0.000 ...  3936.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg31.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 903423  =      0.000 ...  3528.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=903424
    Range : 0 ... 903423 =      0.000 ...  3528.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg32.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1180927  =      0.000 ...  4612.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1180928
    Range : 0 ... 1180927 =      0.000 ...  4612.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg33.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 959231  =      0.000 ...  3746.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=959232
    Range : 0 ... 959231 =      0.000 ...  3746.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg34.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1661695  =      0.000 ...  6490.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1661696
    Range : 0 ... 1661695 =      0.000 ...  6490.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg35.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 964351  =      0.000 ...  3766.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=964352
    Range : 0 ... 964351 =      0.000 ...  3766.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg36.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1300991  =      0.000 ...  5081.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1300992
    Range : 0 ... 1300991 =      0.000 ...  5081.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg37.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1171967  =      0.000 ...  4577.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1171968
    Range : 0 ... 1171967 =      0.000 ...  4577.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg38.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1560319  =      0.000 ...  6094.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1560320
    Range : 0 ... 1560319 =      0.000 ...  6094.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg39.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1185023  =      0.000 ...  4628.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1185024
    Range : 0 ... 1185023 =      0.000 ...  4628.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg40.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1494271  =      0.000 ...  5836.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=888320
    Range : 0 ... 888319 =      0.000 ...  3469.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg54.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1112063  =      0.000 ...  4343.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1112064
    Range : 0 ... 1112063 =      0.000 ...  4343.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg55.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1321215  =      0.000 ...  5160.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1321216
    Range : 0 ... 1321215 =      0.000 ...  5160.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg56.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 980735  =      0.000 ...  3830.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=980736
    Range : 0 ... 980735 =      0.000 ...  3830.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg57.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 802047  =      0.000 ...  3132.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=802048
    Range : 0 ... 802047 =      0.000 ...  3132.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg58.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1199359  =      0.000 ...  4684.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1199360
    Range : 0 ... 1199359 =      0.000 ...  4684.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg59.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1004287  =      0.000 ...  3922.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1004288
    Range : 0 ... 1004287 =      0.000 ...  3922.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg60.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 967423  =      0.000 ...  3778.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=967424
    Range : 0 ... 967423 =      0.000 ...  3778.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg61.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1492223  =      0.000 ...  5828.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1492224
    Range : 0 ... 1492223 =      0.000 ...  5828.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg62.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1498111  =      0.000 ...  5851.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1498112
    Range : 0 ... 1498111 =      0.000 ...  5851.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg63.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 998399  =      0.000 ...  3899.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=998400
    Range : 0 ... 998399 =      0.000 ...  3899.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg64.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1622271  =      0.000 ...  6336.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1622272
    Range : 0 ... 1622271 =      0.000 ...  6336.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg65.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1228799  =      0.000 ...  4799.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1228800
    Range : 0 ... 1228799 =      0.000 ...  4799.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg66.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 2905599  =      0.000 ... 11349.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=2905600
    Range : 0 ... 2905599 =      0.000 ... 11349.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg67.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1254399  =      0.000 ...  4899.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1254400
    Range : 0 ... 1254399 =      0.000 ...  4899.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg68.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 925439  =      0.000 ...  3614.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=925440
    Range : 0 ... 925439 =      0.000 ...  3614.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg69.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1017087  =      0.000 ...  3972.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1017088
    Range : 0 ... 1017087 =      0.000 ...  3972.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg70.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1255935  =      0.000 ...  4905.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1255936
    Range : 0 ... 1255935 =      0.000 ...  4905.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg71.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1094655  =      0.000 ...  4275.996 secs...
EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1094656
    Range : 0 ... 1094655 =      0.000 ...  4275.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg72.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1279487  =      0.000 ...  4997.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1279488
    Range : 0 ... 1279487 =      0.000 ...  4997.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg73.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 954879  =      0.000 ...  3729.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=954880
    Range : 0 ... 954879 =      0.000 ...  3729.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg74.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1117183  =      0.000 ...  4363.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1117184
    Range : 0 ... 1117183 =      0.000 ...  4363.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg75.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1012479  =      0.000 ...  3954.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1012480
    Range : 0 ... 1012479 =      0.000 ...  3954.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg76.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 978175  =      0.000 ...  3820.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=978176
    Range : 0 ... 978175 =      0.000 ...  3820.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg77.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1073407  =      0.000 ...  4192.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1073408
    Range : 0 ... 1073407 =      0.000 ...  4192.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg78.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 1272575  =      0.000 ...  4970.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=1272576
    Range : 0 ... 1272575 =      0.000 ...  4970.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz
Extracting EDF parameters from C:\bt23ece064\dataset\eeg79.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 844031  =      0.000 ...  3296.996 secs...

C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different highpass filters. Highest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_4324\1641202550.py:2: RuntimeWarning: Channels contain different lowpass filters. Lowest filter setting will be stored.
  raw = mne.io.read_raw_edf(filename, preload=True)

EEG channel type selected for re-referencing
Creating RawArray with float64 data, n_channels=18, n_times=844032
    Range : 0 ... 844031 =      0.000 ...  3296.996 secs
Ready.
Added the following bipolar channels:
Fp2-F4, F4-C4, C4-P4, P4-O2, Fp1-F3, F3-C3, C3-P3, P3-O1, Fp2-F8, F8-T4, T4-T6, T6-O2, Fp1-F7, F7-T3, T3-T5, T5-O1, Fz-Cz, Cz-Pz

In [ ]:
# %pip install --upgrade openpyxl 
annotations = pd.read_excel('C:/bt23ece064/dataset/seizure_per_channel_Dec_2017.xlsx')

In [ ]:
annotations

,FILE ID,Start,Stop,Fp2-F4,F4-C4,C4-P4,P4-O2,Fp1-F3,F3-C3,C3-P3,...,Fp2-F8,F8-T4,T4-T6,T6-O2,Fp1-F7,F7-T3,T3-T5,T5-O1,Fz-Cz,Cz-Pz
0,NaN,NaN,NaN,1,2,3,4,5,6,7,...,9,10,11,12,13,14,15,16,17,18
1,1.0,104.0,122.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2,1.0,349.0,428.0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1.0,760.0,779.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4,1.0,956.0,965.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,79.0,152.0,190.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
361,79.0,367.0,384.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
362,79.0,576.0,621.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
363,79.0,2148.0,2163.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
364,79.0,2452.0,2491.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [ ]:
annotations = annotations.sort_values(by=['FILE ID','Start'], ascending=[True,True])

In [ ]:
annotations = annotations.dropna(axis=0)

In [ ]:
seizured_segments =  [np.array(np.zeros((len(eeg[0]),18))) for eeg in eeg_set]
non_seizured_segments =[ [[np.zeros((len(eeg[0]),18)) for eeg in eeg_set]]]

In [ ]:
annotations

,FILE ID,Start,Stop,Fp2-F4,F4-C4,C4-P4,P4-O2,Fp1-F3,F3-C3,C3-P3,...,Fp2-F8,F8-T4,T4-T6,T6-O2,Fp1-F7,F7-T3,T3-T5,T5-O1,Fz-Cz,Cz-Pz
1,1.0,104.0,122.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
2,1.0,349.0,428.0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,1.0,760.0,779.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
4,1.0,956.0,965.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
5,1.0,973.0,982.0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,79.0,152.0,190.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
361,79.0,367.0,384.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
362,79.0,576.0,621.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
363,79.0,2148.0,2163.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
364,79.0,2452.0,2491.0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,1

In [ ]:
iter = annotations.columns[3:]
iter

Index(['Fp2-F4', 'F4-C4', 'C4-P4', 'P4-O2', 'Fp1-F3', 'F3-C3', 'C3-P3',
       'P3-O1', 'Fp2-F8', 'F8-T4', 'T4-T6', 'T6-O2', 'Fp1-F7', 'F7-T3',
       'T3-T5', 'T5-O1', 'Fz-Cz', 'Cz-Pz'],
      dtype='object')

In [ ]:
for i in range(364):
    patient = annotations['FILE ID'].iloc[i]
    start = annotations['Start'].iloc[i]
    end = annotations['End'].iloc[i]
    for col_idx,col in enumerate(iter):
        if annotations[col].iloc[i] == 1:
            for ran in range(start*256, end*256):
                seizured_segments[patient][col_idx][start*256:end*256] = eeg_set[patient][col_idx][start*256:end*256]

TypeError: list indices must be integers or slices, not str

In [ ]:
seizured_segments[0][0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [ ]:
eeg_set[0][0]

array([0.00000000e+00, 1.52587771e-07, 1.06811440e-06, ...,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

KeyboardInterrupt:

In [ ]:
import numpy as np

# Initialize with zeros - same shape as original eeg_set
seizured_segments = [np.zeros_like(eeg) for eeg in eeg_set]
non_seizured_segments = [np.zeros_like(eeg) for eeg in eeg_set]

# Channel columns from your annotations
channel_cols = ['Fp2-F4', 'F4-C4', 'C4-P4', 'P4-O2', 'Fp1-F3', 'F3-C3', 'C3-P3',
                'Fp2-F8', 'F8-T4', 'T4-T6', 'T6-O2', 'Fp1-F7', 'F7-T3', 'T3-T5', 
                'T5-O1', 'Fz-Cz', 'Cz-Pz']

print(f"Starting processing {len(annotations)} annotations...")
print(f"Total patients in eeg_set: {len(eeg_set)}")

# Simple loop through annotations
for i in range(len(annotations)):
    patient = annotations['FILE ID'].iloc[i] - 1  # Convert to 0-based index
    start = int(annotations['Start'].iloc[i] * 256)  # Convert seconds to samples
    stop = int(annotations['Stop'].iloc[i] * 256)
    
    # Progress tracking
    if i % 50 == 0:  # Print every 50 annotations
        print(f"Processing annotation {i+1}/{len(annotations)} - Patient {patient+1}, Time: {annotations['Start'].iloc[i]:.1f}s-{annotations['Stop'].iloc[i]:.1f}s")
    
    seizure_count = 0
    non_seizure_count = 0
    
    # Loop through each channel
    for ch_idx, col in enumerate(channel_cols):
        if ch_idx < len(eeg_set[patient]):  # Make sure channel exists
            if annotations[col].iloc[i] == 1:  # Seizure
                seizured_segments[patient][ch_idx][start:stop] = eeg_set[patient][ch_idx][start:stop]
                non_seizured_segments[patient][ch_idx][start:stop] = 0
                seizure_count += 1
            else:  # Non-seizure
                seizured_segments[patient][ch_idx][start:stop] = 0
                non_seizured_segments[patient][ch_idx][start:stop] = eeg_set[patient][ch_idx][start:stop]
                non_seizure_count += 1
    
    # Print channel summary for first few annotations
    if i < 5:
        print(f"  Annotation {i+1}: {seizure_count} seizure channels, {non_seizure_count} non-seizure channels")

print("\nProcessing complete!")
print(f"Total annotations processed: {len(annotations)}")
print("Both arrays have same shape as original eeg_set")

# Summary statistics
total_seizure_samples = sum([np.count_nonzero(seg) for seg in seizured_segments])
total_non_seizure_samples = sum([np.count_nonzero(seg) for seg in non_seizured_segments])
print(f"Total seizure samples across all patients: {total_seizure_samples}")
print(f"Total non-seizure samples across all patients: {total_non_seizure_samples}")